### ISSUE TITLE
MPP issues

### ISSUE THREAD

**Issue by kiwi0fruit** [kiwi0fruit/atom-jupyter-pandoc-markdown#1]
* [x] ~[Image size bug in MPP](https://github.com/atom-community/markdown-preview-plus/issues/405)~
* [ ] [Save As PDF makes font colors darker](https://github.com/atom-community/markdown-preview-plus/issues/393)
* [ ] [Empty lines in code blocks dissapper](https://github.com/atom-community/markdown-preview-plus/issues/398)
* [ ] Check cross-references links
